# This is a basic workflow to help you get started with Actions

name: Repack localized DLC to CIA

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare resources
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          wget 

      - name: Upload to GitHub release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} > token.txt
          wget https://github.com/cli/cli/releases/download/v2.1.0/gh_2.1.0_linux_amd64.deb
          sudo dpkg -i gh_2.1.0_linux_amd64.deb
          gh auth login --with-token < token.txt
          gh release upload v1.0 rom_tools.tar.gz --clobber 
